package uk.nhs.hee.tis.usermanagement.mapper;

import org.springframework.stereotype.Component;
import software.amazon.awssdk.services.cognitoidentityprovider.model.AdminCreateUserRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.AdminUpdateUserAttributesRequest;
import uk.nhs.hee.tis.usermanagement.DTOs.AuthenticationUserDto;
import uk.nhs.hee.tis.usermanagement.DTOs.CreateUserDTO;

/**
 * Implementation of mapping from usermanagement to cognito requests objects, created as a quick way
 * to upgrade the aws sdk v1 -> v2 This class was modified from the source generated by Mapstruct
 *
 * @Generated{value = "org.mapstruct.ap.MappingProcessor", date = "2025-07-14T08:51:00+0100",
 *     comments = "version: 1.5.5.Final, compiler: javac, environment: Java 11.0.19 (Ubuntu)"}
 */
@Component
public class CognitoRequestMapperImpl extends CognitoRequestMapper {

  @Override
  public AdminCreateUserRequest toCreateUserRequest(CreateUserDTO createUserDto) {
    if (createUserDto == null) {
      return null;
    }

    return AdminCreateUserRequest.builder()
        .username(createUserDto.getName())
        .userAttributes(extractAttributes(createUserDto))
        .build();
  }

  @Override
  public AdminUpdateUserAttributesRequest toUpdateUserRequest(
      AuthenticationUserDto authenticationUser) {
    if (authenticationUser == null) {
      return null;
    }

    return AdminUpdateUserAttributesRequest.builder()
        .userAttributes(extractAttributes(authenticationUser))
        .username(authenticationUser.getUsername())
        .build();
  }
}
